services:
  servidor:
    build: .
    container_name: caronas-servidor
    ports:
      - "6000:6000"

    stop_signal: SIGINT
  testes:
    build: .
    command: python testes.py

  motorista:
    build: .
    command: python motorista.py
    environment:
      SERVIDOR: servidor
    depends_on:
      - servidor
    stdin_open: true
    tty: true

  passageiro:
    build: .
    command: python passageiro.py
    environment:
      SERVIDOR: servidor
    depends_on:
      - servidor
    stdin_open: true
    tty: true
